### ISSUE TITLE
Can not build rust-ffmpeg-sys both on Fedora and Ubuntu 16.04

### ISSUE THREAD

**Issue by bioothod** [meh/rust-ffmpeg-sys#62]
Hi

I've came here originally because of rust-ffmpeg build failure, but it seems that there is an issue related to how bindgen tries to compile sys bindings. Problem persists both with native ffmpeg and when "build" feature is enabled (i.e. downloaded lib).

In a nutshell, here is an output:```
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")

/usr/include/limits.h:124:16: fatal error: 'limits.h' file not found
/usr/include/limits.h:124:16: fatal error: 'limits.h' file not found, err: true
thread 'main' panicked at 'Unable to generate bindings: ()', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I use pretty much default linux installations with ffmpeg devel packages installed as well as other devel stuff from libc, libstdc++ and so on. I'm pretty sure this is somehow related to one or another missing header and/or compiler options, but error output is pretty cryptic.

Attached full outputs for cloned and native ffmpeg builds.

Any advice on how to debug this?

[build_cloned_ffmpeg.txt](https://github.com/meh/rust-ffmpeg-sys/files/2000880/build_cloned_ffmpeg.txt)
[build_native_ffmpeg.txt](https://github.com/meh/rust-ffmpeg-sys/files/2000881/build_native_ffmpeg.txt)

**Comment by bioothod** [comment]
Looks like solution is to install clang-4.0 which brings llvm-4.0
At least it works on ubuntu 16.04, I will check fedora and update this issue

**Comment by bioothod** [comment]
Installing clang package itself (not only stdc++ library) solves this issue
