### PR TITLE
Fix builds on Rust 1.39

### LINKED ISSUE #78: Can't compile with Rust 1.39
With rust 1.39 is not possible to compile this crate anymore, I get the followig errors. Do you have any ideas?

```
error[E0369]: binary operation `==` cannot be applied to type `__mbstate_t__bindgen_ty_1`
    --> /home/andrea/Workspace/git/video_ludo/target/debug/build/ffmpeg-sys-77d9e656be992a77/out/bindings.rs:3000:5
     |
3000 |     pub __value: __mbstate_t__bindgen_ty_1,
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: an implementation of `std::cmp::PartialEq` might be missing for `__mbstate_t__bindgen_ty_1`

error[E0369]: binary operation `!=` cannot be applied to type `__mbstate_t__bindgen_ty_1`
    --> /home/andrea/Workspace/git/video_ludo/target/debug/build/ffmpeg-sys-77d9e656be992a77/out/bindings.rs:3000:5
     |
3000 |     pub __value: __mbstate_t__bindgen_ty_1,
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: an implementation of `std::cmp::PartialEq` might be missing for `__mbstate_t__bindgen_ty_1`

error[E0277]: the trait bound `__mbstate_t__bindgen_ty_1: std::cmp::Eq` is not satisfied
    --> /home/andrea/Workspace/git/video_ludo/target/debug/build/ffmpeg-sys-77d9e656be992a77/out/bindings.rs:3000:5
     |
3000 |     pub __value: __mbstate_t__bindgen_ty_1,
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::cmp::Eq` is not implemented for `__mbstate_t__bindgen_ty_1`
     |
     = note: required by `std::cmp::AssertParamIsEq`
```

### PR DESCRIPTION
**Pull request by danieldulaney**
Closes #78 and obsoletes #79.

### CODE REVIEW

**Comment by danieldulaney** [comment]
Ok, that was an odyssey. In summary:

- bindgen pre-0.51.1 is broken on Rust 1.39, so bindgen is upgraded to 0.51.1.
- bindgen changed how they handle macros inside enums, so the macro blacklisting had to be changed.
- bindgen also changed how they generate code -- they now dump everything onto one line, then run rustfmt on it. With rustfmt missing, that leaves everything on one line, which isn't a problem except that bindgen now generates `u128`s for C's `long double`s, which cause warnings, which print out the entire file to stdout for each warning, which causes TravisCI to error out with too many logs. The easy fix: just add rustfmt to the build environment. Everything else will have to wait on bindgen.
- bindgen also got smart(er) about sanitizing C comments, but not enough, because it still leaves indents alone, which get recognized as code blocks by rustdoc, which tries to run the comments as doctests, which obviously fail. The workaround is disabling doctests altogether until bindgen fixes this.
- while we're here, update the other build deps to their latest versions and fix some build.rs warnings.

The only major tradeoff is disabling doctests crate-wide. Unfortunately, setting #[doc(test(ignore))] doesn't prevent rustdoc from attempting to compile them, which fails (because English isn't generally valid Rust). This is a big hammer, but it's all we have until bindgen or rustdoc get fixed. (Note: See https://github.com/rust-lang/rust/issues/59867 for the issue progress)

However, it now all works. I can finally recommend merging this PR. I'm happy to bundle these up into a single commit if that's preferred.

**Comment by AndreaCatania** [comment]
Now it compile for me.

**Comment by meh** [comment]
Sounds good to me, I was fine with the git history. Thanks!
